services:
    db:
        image: mysql:8.4
        hostname: db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db_internet_monitoring
            MYSQL_USER: user
            MYSQL_PASSWORD: user
        volumes:
            - ./db_data:/var/lib/mysql
            - ./dump:/dump
        ports:
            - "3314:3306"
        networks:
            - monitoring-net
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
            interval: 5s
            timeout: 5s
            retries: 20

    app:
        build: .
        depends_on:
            db:
                condition: service_healthy
        working_dir: /app
        environment:
            DB_HOST: db
            DB_USER: root
            DB_PASSWORD: root
            DB_NAME: db_internet_monitoring
            PYTHONPATH: /app
        restart: always
        volumes:
            - .:/app
        command: poetry run python app/speed_test.py
        networks:
            - monitoring-net

networks:
    monitoring-net:
